name: one-ck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#jobs:
#  tests:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: php -v
#      run: php -v
#    - name: install clickhouse
#      run: docker run -p 127.0.0.1:9000:9000 -p 127.0.0.1:8123:8123 -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
#    - name: Install Dependencies
#      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
#    - name: Execute tests
#      run: php test.php


jobs:
  run:
    runs-on: self-hosted
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0']
    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
        env:
          runner: self-hosted # Specify the runner.
      - name: php -v
        run: php -v
      - name: install clickhouse
        run: docker run -p 127.0.0.1:9000:9000 -p 127.0.0.1:8123:8123 -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Execute tests
        run: php test.php

